Reciever: Socket_reciever.cpp 
	g++ Socket_reciever.cpp -o Reciever

Sender: Socket_sender.cpp
	g++ Socket_sender.cpp -o Sender

UDP: UDPReciver.cpp
	g++ UDPReciver.cpp -o UDP


clean:
	rm -f *.o program